/** Base map definitions — coordinates from bible-locations.js (scholarly site IDs) */
const LOC = require("./bible-locations.js");
const { pt, coords: c, geoFromKeys: geo } = LOC;

module.exports = function buildCatalog(ctx) {
  const { baseMap, COV, NAT, NORTH, SOUTH, CHURCH, EMPIRE } = ctx;

  const abrahamGeo = geo(["ur", "haran", "shechem", "bethel", "hebron", "beersheba", "goshen", "moriah"], 4, 3, 6);
  const exodusGeo = geo(["rameses", "succoth", "pi_hahiroth", "red_sea", "sinai", "kadesh", "jericho", "gilgal"], 3, 2.5, 8);
  const judgesGeo = geo(["megiddo", "tabor", "kishon", "ophrah", "jezreel", "zorah", "shiloh"], 2.5, 2, 9);
  const davidGeo = geo(["bethlehem", "elah", "hebron", "jerusalem", "en_gedi", "ziklag", "keilah"], 2.5, 2, 10);
  const solomonGeo = geo(["gibeon", "temple_mount", "tyre", "ezion_geber"], 4, 5, 9);
  const splitGeo = geo(["jerusalem", "shechem", "tirzah", "samaria", "bethel", "dan"], 3, 3, 9);
  const prophetsGeo = geo(["carmel", "samaria", "jerusalem", "anathoth", "lachish", "nineveh", "tel_abib", "babylon"], 6, 4, 7);
  const israelFallGeo = geo(["samaria", "nineveh"], 8, 6, 8);
  const judahFallGeo = geo(["jerusalem", "lachish", "babylon"], 6, 4, 10);
  const jesusGeo = geo(["bethlehem", "nazareth", "cana", "capernaum", "galilee_sea", "jericho", "bethany", "gethsemane", "jerusalem", "emmaus"], 3, 2.5, 10);
  const paulGeo = geo(["damascus", "antioch_syria", "salamis", "pisidian_antioch", "iconium", "lystra", "troas", "philippi", "thessalonica", "athens", "corinth", "ephesus", "caesarea", "jerusalem", "rome"], 8, 6, 5);
  const gospelEuGeo = geo(["jerusalem", "rome", "alexandria", "constantinople", "milan", "moravia", "kiev"], 12, 10, 5);
  const crusadesGeo = geo(["clermont", "nicaea", "antioch", "jerusalem", "hattin", "acre"], 10, 8, 6);
  const schismGeo = geo(["rome", "constantinople", "alexandria", "antioch"], 10, 8, 5);

  return [
    {
      slug: "abraham",
      title_zh: "亞伯拉罕生平",
      title_en: "ABRAHAM",
      blurb: "蒙召、遷徙、應許之地",
      period: "約公元前2000年",
      places: "吾珥 · 哈蘭 · 示劍 · 希伯崙 · 摩利亞",
      data: baseMap("abraham", "亞伯拉罕生平", "ABRAHAM'S JOURNEY", "創12–25章", abrahamGeo, COV, NAT, abrahamGeo.center, {
        narr_zh: "耶和華對亞伯蘭說：你要離開本地本族，往我所要指示你的地去。",
        narr_en: "The LORD said to Abram: Go from your country to the land I will show you.",
        points: [pt("ur"), pt("haran"), pt("shechem"), pt("bethel"), pt("hebron"), pt("beersheba"), pt("gerar"), pt("goshen"), pt("moriah")],
        units: [
          {
            id: "abram",
            faction: "covenant",
            kind: "command",
            crest: "shield",
            cf: true,
            name_zh: "亞伯蘭一家",
            name_en: "Abram's household",
            track: [
              { d: 1, lng: c("ur")[0], lat: c("ur")[1], s: 0, st: "hold" },
              { d: 18, lng: c("haran")[0], lat: c("haran")[1], s: 0, st: "hold" },
              { d: 38, lng: c("shechem")[0], lat: c("shechem")[1], s: 0, st: "hold" },
              { d: 48, lng: c("bethel")[0], lat: c("bethel")[1], s: 0, st: "hold" },
              { d: 58, lng: c("hebron")[0], lat: c("hebron")[1], s: 0, st: "hold" },
              { d: 72, lng: c("goshen")[0], lat: c("goshen")[1], s: 0, st: "hold" },
              { d: 82, lng: c("hebron")[0], lat: c("hebron")[1], s: 0, st: "hold" },
              { d: 100, lng: c("moriah")[0], lat: c("moriah")[1], s: 0, st: "hold" },
            ],
          },
        ],
        arrows: [
          { d: 10, f: "covenant", from: c("ur"), to: c("haran"), label: "離開吾珥 創12:4", kind: "retreat" },
          { d: 32, f: "covenant", from: c("haran"), to: c("shechem"), label: "進入迦南 創12:5", kind: "attack" },
          { d: 68, f: "covenant", from: c("hebron"), to: c("goshen"), label: "饑荒下埃及 創12:10", kind: "retreat" },
          { d: 92, f: "covenant", from: c("hebron"), to: c("moriah"), label: "獻以撒 創22:2", kind: "attack" },
        ],
      }),
    },
    {
      slug: "exodus-canaan",
      title_zh: "出埃及與進迦南",
      title_en: "EXODUS & CONQUEST",
      blurb: "出埃及、曠野、約書亞征戰",
      period: "約公元前1446–1400年",
      places: "蘭塞 · 紅海 · 西奈 · 加低斯 · 耶利哥",
      data: baseMap("exodus", "出埃及與進迦南", "EXODUS & CONQUEST", "出–書", exodusGeo, COV, NAT, exodusGeo.center, {
        narr_zh: "我必救你脫離埃及人的苦難，領你進入美好寬闊流奶與蜜之地。",
        narr_en: "I will bring you up out of Egypt to a land flowing with milk and honey.",
        points: [pt("rameses"), pt("succoth"), pt("pi_hahiroth"), pt("red_sea"), pt("sinai"), pt("rephidim"), pt("kadesh"), pt("jericho"), pt("gilgal"), pt("ai")],
        units: [
          {
            id: "israel_ex",
            faction: "covenant",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "以色列人",
            name_en: "Israelites",
            track: [
              { d: 1, lng: c("rameses")[0], lat: c("rameses")[1], s: 600000, st: "hold" },
              { d: 12, lng: c("succoth")[0], lat: c("succoth")[1], s: 600000, st: "retreat" },
              { d: 22, lng: c("pi_hahiroth")[0], lat: c("pi_hahiroth")[1], s: 600000, st: "hold" },
              { d: 30, lng: c("red_sea")[0], lat: c("red_sea")[1], s: 600000, st: "hold" },
              { d: 45, lng: c("sinai")[0], lat: c("sinai")[1], s: 500000, st: "hold" },
              { d: 55, lng: c("rephidim")[0], lat: c("rephidim")[1], s: 500000, st: "hold" },
              { d: 70, lng: c("kadesh")[0], lat: c("kadesh")[1], s: 450000, st: "hold" },
              { d: 88, lng: c("gilgal")[0], lat: c("gilgal")[1], s: 400000, st: "hold" },
              { d: 100, lng: c("jericho")[0], lat: c("jericho")[1], s: 400000, st: "attack" },
            ],
          },
          {
            id: "egypt_ex",
            faction: "nations",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "埃及軍",
            name_en: "Egyptian army",
            track: [
              { d: 24, lng: c("pi_hahiroth")[0], lat: c("pi_hahiroth")[1], s: 80000, st: "attack" },
              { d: 32, lng: c("red_sea")[0], lat: c("red_sea")[1], s: 0, st: "dead" },
            ],
          },
        ],
        arrows: [
          { d: 8, f: "covenant", from: c("rameses"), to: c("succoth"), label: "出埃及 出12:37", kind: "retreat" },
          { d: 28, f: "covenant", from: c("pi_hahiroth"), to: c("red_sea"), label: "過紅海 出14:22", kind: "retreat" },
          { d: 85, f: "covenant", from: c("gilgal"), to: c("jericho"), label: "攻耶利哥 書6:20", kind: "attack" },
        ],
        hotspots: [
          { a: 26, b: 36, lng: c("red_sea")[0], lat: c("red_sea")[1], kind: "landing", i: 0.85 },
          { a: 92, b: 100, lng: c("jericho")[0], lat: c("jericho")[1], kind: "firefight", i: 0.9 },
        ],
      }),
    },
    {
      slug: "judges",
      title_zh: "士師時代",
      title_en: "JUDGES",
      blurb: "底波拉、基甸、參孫等士師",
      period: "約公元前1400–1050年",
      places: "他泊 · 基順 · 俄弗拉 · 瑣拉 · 米吉多",
      data: baseMap("judges", "士師時代", "ERA OF JUDGES", "士師記", judgesGeo, COV, NAT, judgesGeo.center, {
        narr_zh: "以色列人又行耶和華眼中看為惡的事，耶和華就把他們交在仇敵手中。",
        narr_en: "Israel did evil again; the LORD gave them into the hand of their enemies.",
        points: [pt("shiloh"), pt("megiddo"), pt("tabor"), pt("kishon"), pt("ophrah"), pt("jezreel"), pt("zorah"), pt("gibeah")],
        units: [
          {
            id: "judges_is",
            faction: "covenant",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "以色列",
            name_en: "Israel",
            track: [
              { d: 1, lng: c("shiloh")[0], lat: c("shiloh")[1], s: 40000, st: "hold" },
              { d: 30, lng: c("tabor")[0], lat: c("tabor")[1], s: 10000, st: "attack" },
              { d: 50, lng: c("ophrah")[0], lat: c("ophrah")[1], s: 300, st: "attack" },
              { d: 75, lng: c("zorah")[0], lat: c("zorah")[1], s: 1, st: "hold" },
              { d: 100, lng: c("shiloh")[0], lat: c("shiloh")[1], s: 50000, st: "hold" },
            ],
          },
          {
            id: "judges_en",
            faction: "nations",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "米甸／非利士",
            name_en: "Midian / Philistines",
            track: [
              { d: 25, lng: c("kishon")[0], lat: c("kishon")[1], s: 90000, st: "attack" },
              { d: 40, lng: c("jezreel")[0], lat: c("jezreel")[1], s: 0, st: "dead" },
              { d: 70, lng: c("zorah")[0], lat: c("zorah")[1], s: 30000, st: "attack" },
              { d: 85, lng: c("zorah")[0], lat: c("zorah")[1], s: 5000, st: "retreat" },
            ],
          },
        ],
        hotspots: [
          { a: 28, b: 45, lng: c("kishon")[0], lat: c("kishon")[1], kind: "firefight", i: 0.85 },
          { a: 48, b: 58, lng: c("ophrah")[0], lat: c("ophrah")[1], kind: "firefight", i: 0.7 },
        ],
      }),
    },
    {
      slug: "david",
      title_zh: "大衛時期",
      title_en: "KING DAVID",
      blurb: "牧童、歌利亞、希伯崙、耶路撒冷",
      period: "約公元前1010–970年",
      places: "伯利恆 · 以拉谷 · 希伯崙 · 耶路撒冷",
      data: baseMap("david", "大衛時期", "KING DAVID", "撒上–撒下", davidGeo, COV, NAT, c("jerusalem"), {
        narr_zh: "大衛作以色列眾人的王，又作猶大人的王七年零六個月。",
        narr_en: "David reigned over all Israel and Judah.",
        points: [pt("bethlehem"), pt("elah"), pt("keilah"), pt("en_gedi"), pt("ziklag"), pt("hebron"), pt("jerusalem")],
        units: [
          {
            id: "david_army",
            faction: "covenant",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "大衛",
            name_en: "David",
            track: [
              { d: 1, lng: c("bethlehem")[0], lat: c("bethlehem")[1], s: 1000, st: "hold" },
              { d: 25, lng: c("elah")[0], lat: c("elah")[1], s: 3000, st: "attack" },
              { d: 45, lng: c("en_gedi")[0], lat: c("en_gedi")[1], s: 600, st: "hold" },
              { d: 65, lng: c("hebron")[0], lat: c("hebron")[1], s: 20000, st: "hold" },
              { d: 100, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 50000, st: "hold" },
            ],
          },
          {
            id: "philistines",
            faction: "nations",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "非利士人",
            name_en: "Philistines",
            track: [
              { d: 20, lng: c("elah")[0], lat: c("elah")[1], s: 20000, st: "attack" },
              { d: 32, lng: c("elah")[0], lat: c("elah")[1] - 0.04, s: 5000, st: "retreat" },
            ],
          },
        ],
        hotspots: [{ a: 22, b: 35, lng: c("elah")[0], lat: c("elah")[1], kind: "firefight", i: 0.85 }],
      }),
    },
    {
      slug: "solomon",
      title_zh: "所羅門時期",
      title_en: "KING SOLOMON",
      blurb: "基遍求智慧、建殿、推羅、以旬迦別",
      period: "約公元前970–931年",
      places: "基遍 · 耶路撒冷 · 推羅 · 以旬迦別",
      data: baseMap("solomon", "所羅門時期", "KING SOLOMON", "王上1–11", solomonGeo, COV, NAT, c("jerusalem"), {
        narr_zh: "所羅門在耶路撒冷作以色列眾人的王；他作王四十年。",
        narr_en: "Solomon reigned in Jerusalem over all Israel forty years.",
        points: [pt("gibeon"), pt("temple_mount"), pt("tyre"), pt("ezion_geber")],
        units: [
          {
            id: "solomon",
            faction: "covenant",
            kind: "command",
            crest: "shield",
            cf: true,
            name_zh: "所羅門王國",
            name_en: "Solomon's kingdom",
            track: [
              { d: 1, lng: c("gibeon")[0], lat: c("gibeon")[1], s: 0, st: "hold" },
              { d: 35, lng: c("temple_mount")[0], lat: c("temple_mount")[1], s: 80000, st: "hold" },
              { d: 60, lng: c("tyre")[0], lat: c("tyre")[1], s: 0, st: "hold" },
              { d: 80, lng: c("ezion_geber")[0], lat: c("ezion_geber")[1], s: 0, st: "hold" },
              { d: 100, lng: c("temple_mount")[0], lat: c("temple_mount")[1], s: 90000, st: "hold" },
            ],
          },
        ],
        arrows: [{ d: 55, f: "covenant", from: c("temple_mount"), to: c("tyre"), label: "與推羅合作 王上5:1", kind: "attack" }],
      }),
    },
    {
      slug: "kingdom-split",
      title_zh: "國度分裂",
      title_en: "KINGDOM DIVIDED",
      blurb: "示劍叛變、得撒、但與伯特利",
      period: "公元前931年",
      places: "示劍 · 得撒 · 撒瑪利亞 · 伯特利 · 但",
      data: baseMap("split", "國度分裂", "DIVIDED KINGDOM", "王上12", splitGeo, null, null, splitGeo.center, {
        factions: { north: NORTH, south: SOUTH },
        factionOrder: ["north", "south"],
        narr_zh: "於是以色列人背叛大衛家；北方十支派立耶羅波安為王。",
        narr_en: "Israel rebelled against the house of David; Jeroboam became king of the north.",
        points: [pt("shechem"), pt("jerusalem"), pt("tirzah"), pt("samaria"), pt("bethel"), pt("dan")],
        units: [
          {
            id: "judah",
            faction: "south",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "猶大國",
            name_en: "Kingdom of Judah",
            track: [{ d: 1, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 40000, st: "hold" }, { d: 100, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 35000, st: "hold" }],
          },
          {
            id: "israel_n",
            faction: "north",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "以色列國",
            name_en: "Kingdom of Israel",
            track: [
              { d: 1, lng: c("shechem")[0], lat: c("shechem")[1], s: 50000, st: "hold" },
              { d: 40, lng: c("tirzah")[0], lat: c("tirzah")[1], s: 52000, st: "hold" },
              { d: 70, lng: c("samaria")[0], lat: c("samaria")[1], s: 55000, st: "hold" },
            ],
          },
        ],
      }),
    },
    {
      slug: "prophets",
      title_zh: "先知時序與地點",
      title_en: "PROPHETS",
      blurb: "以利亞至被擄先知",
      period: "公元前9–6世紀",
      places: "迦密 · 撒瑪利亞 · 耶路撒冷 · 巴比倫",
      data: baseMap("prophets", "先知時序", "PROPHETS TIMELINE", "先知書", prophetsGeo, COV, NAT, c("jerusalem"), {
        narr_zh: "耶和華的話臨到先知，在猶大與以色列宣告審判與安慰。",
        narr_en: "The word of the LORD came to the prophets in Judah and Israel.",
        points: [pt("carmel"), pt("samaria"), pt("jerusalem"), pt("anathoth"), pt("lachish"), pt("nineveh"), pt("tel_abib"), pt("babylon")],
        units: [
          {
            id: "prophets",
            faction: "covenant",
            kind: "command",
            crest: "shield",
            cf: false,
            name_zh: "先知",
            name_en: "Prophets",
            track: [
              { d: 1, lng: c("carmel")[0], lat: c("carmel")[1], s: 0, st: "hold" },
              { d: 25, lng: c("samaria")[0], lat: c("samaria")[1], s: 0, st: "hold" },
              { d: 45, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 0, st: "hold" },
              { d: 65, lng: c("anathoth")[0], lat: c("anathoth")[1], s: 0, st: "hold" },
              { d: 82, lng: c("tel_abib")[0], lat: c("tel_abib")[1], s: 0, st: "hold" },
              { d: 100, lng: c("babylon")[0], lat: c("babylon")[1], s: 0, st: "hold" },
            ],
          },
        ],
      }),
    },
    {
      slug: "israel-fall",
      title_zh: "以色列亡國",
      title_en: "FALL OF ISRAEL",
      blurb: "撒瑪利亞陷落，被擄亞述",
      period: "公元前722年",
      places: "尼尼微 · 撒瑪利亞",
      data: baseMap("israel-fall", "以色列亡國", "FALL OF ISRAEL", "王下17", israelFallGeo, COV, NAT, c("samaria"), {
        narr_zh: "亞述王攻陷撒瑪利亞，將以色列人擄去亞述。",
        narr_en: "The king of Assyria captured Samaria and deported Israel.",
        points: [pt("nineveh"), pt("samaria")],
        units: [
          {
            id: "samaria",
            faction: "covenant",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "撒瑪利亞",
            name_en: "Samaria",
            track: [{ d: 1, lng: c("samaria")[0], lat: c("samaria")[1], s: 30000, st: "hold" }, { d: 80, lng: c("samaria")[0], lat: c("samaria")[1], s: 5000, st: "dead" }],
          },
          {
            id: "assyria",
            faction: "nations",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "亞述軍",
            name_en: "Assyrian army",
            track: [
              { d: 1, lng: c("nineveh")[0], lat: c("nineveh")[1], s: 80000, st: "attack" },
              { d: 50, lng: c("samaria")[0], lat: c("samaria")[1], s: 75000, st: "attack" },
              { d: 100, lng: c("samaria")[0], lat: c("samaria")[1], s: 70000, st: "hold" },
            ],
          },
        ],
        hotspots: [{ a: 40, b: 100, lng: c("samaria")[0], lat: c("samaria")[1], kind: "firefight", i: 1 }],
      }),
    },
    {
      slug: "judah-fall",
      title_zh: "猶大國亡國",
      title_en: "FALL OF JUDAH",
      blurb: "耶路撒冷與拉吉陷落，被擄巴比倫",
      period: "公元前586年",
      places: "耶路撒冷 · 拉吉 · 巴比倫",
      data: baseMap("judah-fall", "猶大亡國", "FALL OF JUDAH", "王下25", judahFallGeo, COV, NAT, c("jerusalem"), {
        narr_zh: "巴比倫王尼布甲尼撒攻破耶路撒冷，焚燒聖殿。",
        narr_en: "Nebuchadnezzar destroyed Jerusalem and burned the temple.",
        points: [pt("lachish"), pt("jerusalem"), pt("babylon")],
        units: [
          {
            id: "jerusalem",
            faction: "covenant",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "耶路撒冷",
            name_en: "Jerusalem",
            track: [{ d: 1, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 25000, st: "hold" }, { d: 90, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 0, st: "dead" }],
          },
          {
            id: "babylon_army",
            faction: "nations",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "巴比倫軍",
            name_en: "Babylonian army",
            track: [
              { d: 1, lng: c("babylon")[0], lat: c("babylon")[1], s: 100000, st: "attack" },
              { d: 40, lng: c("lachish")[0], lat: c("lachish")[1], s: 90000, st: "attack" },
              { d: 100, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 80000, st: "hold" },
            ],
          },
        ],
        hotspots: [{ a: 50, b: 100, lng: c("jerusalem")[0], lat: c("jerusalem")[1], kind: "artillery", i: 0.9 }],
      }),
    },
    {
      slug: "jesus",
      title_zh: "耶穌生平",
      title_en: "LIFE OF JESUS",
      blurb: "降生、加利利事工、受難、復活",
      period: "公元1世紀",
      places: "伯利恆 · 拿撒勒 · 迦百農 · 耶路撒冷",
      data: baseMap("jesus", "耶穌生平", "LIFE OF JESUS", "四福音", jesusGeo, COV, NAT, c("jerusalem"), {
        narr_zh: "道成了肉身，住在我們中間，充充滿滿地有恩典有真理。",
        narr_en: "The Word became flesh and dwelt among us.",
        points: [pt("bethlehem"), pt("nazareth"), pt("cana"), pt("capernaum"), pt("galilee_sea"), pt("jericho"), pt("bethany"), pt("gethsemane"), pt("jerusalem"), pt("emmaus")],
        units: [
          {
            id: "jesus",
            faction: "covenant",
            kind: "command",
            crest: "shield",
            cf: true,
            name_zh: "耶穌",
            name_en: "Jesus",
            track: [
              { d: 1, lng: c("bethlehem")[0], lat: c("bethlehem")[1], s: 0, st: "hold" },
              { d: 18, lng: c("nazareth")[0], lat: c("nazareth")[1], s: 0, st: "hold" },
              { d: 35, lng: c("cana")[0], lat: c("cana")[1], s: 0, st: "hold" },
              { d: 50, lng: c("capernaum")[0], lat: c("capernaum")[1], s: 0, st: "hold" },
              { d: 65, lng: c("galilee_sea")[0], lat: c("galilee_sea")[1], s: 0, st: "hold" },
              { d: 78, lng: c("jericho")[0], lat: c("jericho")[1], s: 0, st: "hold" },
              { d: 88, lng: c("gethsemane")[0], lat: c("gethsemane")[1], s: 0, st: "hold" },
              { d: 100, lng: c("emmaus")[0], lat: c("emmaus")[1], s: 0, st: "hold" },
            ],
          },
        ],
        arrows: [
          { d: 82, f: "covenant", from: c("bethany"), to: c("jerusalem"), label: "進耶路撒冷 太21:9", kind: "attack" },
        ],
      }),
    },
    {
      slug: "paul",
      title_zh: "保羅傳福音",
      title_en: "PAUL'S JOURNEYS",
      blurb: "大馬士革、三次宣教、羅馬",
      period: "公元33–67年",
      places: "大馬士革 · 安提阿 · 以弗所 · 羅馬",
      data: baseMap("paul", "保羅傳福音", "PAUL'S JOURNEYS", "使徒行傳", paulGeo, COV, NAT, c("antioch_syria"), {
        narr_zh: "保羅行程滿了耶穌的見證，在外邦建立教會。",
        narr_en: "Paul bore witness to Jesus and planted churches among the nations.",
        points: [
          pt("damascus"),
          pt("antioch_syria"),
          pt("salamis"),
          pt("pisidian_antioch"),
          pt("iconium"),
          pt("lystra"),
          pt("troas"),
          pt("philippi"),
          pt("thessalonica"),
          pt("athens"),
          pt("corinth"),
          pt("ephesus"),
          pt("caesarea"),
          pt("jerusalem"),
          pt("rome"),
        ],
        units: [
          {
            id: "paul",
            faction: "covenant",
            kind: "command",
            crest: "shield",
            cf: true,
            name_zh: "保羅一行",
            name_en: "Paul's party",
            track: [
              { d: 1, lng: c("damascus")[0], lat: c("damascus")[1], s: 0, st: "hold" },
              { d: 10, lng: c("antioch_syria")[0], lat: c("antioch_syria")[1], s: 0, st: "hold" },
              { d: 22, lng: c("salamis")[0], lat: c("salamis")[1], s: 0, st: "hold" },
              { d: 30, lng: c("pisidian_antioch")[0], lat: c("pisidian_antioch")[1], s: 0, st: "hold" },
              { d: 38, lng: c("lystra")[0], lat: c("lystra")[1], s: 0, st: "hold" },
              { d: 48, lng: c("troas")[0], lat: c("troas")[1], s: 0, st: "hold" },
              { d: 55, lng: c("philippi")[0], lat: c("philippi")[1], s: 0, st: "hold" },
              { d: 62, lng: c("athens")[0], lat: c("athens")[1], s: 0, st: "hold" },
              { d: 70, lng: c("corinth")[0], lat: c("corinth")[1], s: 0, st: "hold" },
              { d: 80, lng: c("ephesus")[0], lat: c("ephesus")[1], s: 0, st: "hold" },
              { d: 90, lng: c("caesarea")[0], lat: c("caesarea")[1], s: 0, st: "hold" },
              { d: 100, lng: c("rome")[0], lat: c("rome")[1], s: 0, st: "hold" },
            ],
          },
        ],
        arrows: [
          { d: 5, f: "covenant", from: c("damascus"), to: c("antioch_syria"), label: "歸主後 徒9:26", kind: "attack" },
          { d: 18, f: "covenant", from: c("antioch_syria"), to: c("salamis"), label: "第一次宣教 徒13:4", kind: "attack" },
          { d: 95, f: "covenant", from: c("caesarea"), to: c("rome"), label: "上告該撒 徒25:11", kind: "attack" },
        ],
      }),
    },
    {
      slug: "gospel-europe",
      title_zh: "福音傳遍歐洲",
      title_en: "GOSPEL TO EUROPE",
      blurb: "耶路撒冷至羅馬、東歐斯拉夫",
      period: "1–10世紀",
      places: "耶路撒冷 · 羅馬 · 君士坦丁堡 · 基輔",
      data: baseMap("gospel-eu", "福音傳遍歐洲", "GOSPEL IN EUROPE", "教會史", gospelEuGeo, null, null, gospelEuGeo.center, {
        factions: { church: CHURCH, empire: EMPIRE },
        factionOrder: ["church", "empire"],
        narr_zh: "福音從耶路撒冷傳至羅馬，再擴展至東歐與斯拉夫地區。",
        narr_en: "The gospel spread from Jerusalem to Rome and into Eastern Europe.",
        points: [pt("jerusalem"), pt("rome"), pt("alexandria"), pt("milan"), pt("constantinople"), pt("moravia"), pt("kiev")],
        units: [
          {
            id: "church",
            faction: "church",
            kind: "command",
            crest: "shield",
            cf: true,
            name_zh: "教會擴展",
            name_en: "Church expansion",
            track: [
              { d: 1, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 0, st: "hold" },
              { d: 25, lng: c("rome")[0], lat: c("rome")[1], s: 0, st: "hold" },
              { d: 45, lng: c("alexandria")[0], lat: c("alexandria")[1], s: 0, st: "hold" },
              { d: 60, lng: c("constantinople")[0], lat: c("constantinople")[1], s: 0, st: "hold" },
              { d: 78, lng: c("moravia")[0], lat: c("moravia")[1], s: 0, st: "hold" },
              { d: 100, lng: c("kiev")[0], lat: c("kiev")[1], s: 0, st: "hold" },
            ],
          },
        ],
      }),
    },
    {
      slug: "crusades",
      title_zh: "十字軍東征",
      title_en: "CRUSADES",
      blurb: "克萊蒙號召至阿卡陷落",
      period: "1095–1291",
      places: "克萊蒙 · 安條克 · 耶路撒冷 · 哈丁 · 阿卡",
      data: baseMap("crusades", "十字軍東征", "THE CRUSADES", "1095–1291", crusadesGeo, null, null, c("jerusalem"), {
        factions: { church: CHURCH, empire: EMPIRE },
        factionOrder: ["church", "empire"],
        narr_zh: "教皇烏爾班二世在克萊蒙號召收復聖地；十字軍多次遠征耶路撒冷。",
        narr_en: "Pope Urban II called for the recovery of the Holy Land at Clermont.",
        points: [pt("clermont"), pt("nicaea"), pt("antioch"), pt("jerusalem"), pt("hattin"), pt("acre")],
        units: [
          {
            id: "crusaders",
            faction: "church",
            kind: "infantry",
            crest: "shield",
            cf: true,
            name_zh: "十字軍",
            name_en: "Crusaders",
            track: [
              { d: 1, lng: c("clermont")[0], lat: c("clermont")[1], s: 50000, st: "hold" },
              { d: 25, lng: c("nicaea")[0], lat: c("nicaea")[1], s: 45000, st: "attack" },
              { d: 45, lng: c("antioch")[0], lat: c("antioch")[1], s: 42000, st: "attack" },
              { d: 65, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 40000, st: "hold" },
            ],
          },
          {
            id: "ayyubids",
            faction: "empire",
            kind: "infantry",
            crest: "circle",
            cf: true,
            name_zh: "穆斯林聯軍",
            name_en: "Muslim forces",
            track: [
              { d: 1, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 60000, st: "hold" },
              { d: 75, lng: c("hattin")[0], lat: c("hattin")[1], s: 65000, st: "attack" },
              { d: 90, lng: c("jerusalem")[0], lat: c("jerusalem")[1], s: 60000, st: "hold" },
              { d: 100, lng: c("acre")[0], lat: c("acre")[1], s: 55000, st: "attack" },
            ],
          },
        ],
        hotspots: [
          { a: 40, b: 55, lng: c("antioch")[0], lat: c("antioch")[1], kind: "firefight", i: 0.8 },
          { a: 72, b: 88, lng: c("hattin")[0], lat: c("hattin")[1], kind: "firefight", i: 0.9 },
        ],
      }),
    },
    {
      slug: "church-schism",
      title_zh: "教會分裂史",
      title_en: "GREAT SCHISM",
      blurb: "1054東西教會分裂",
      period: "1054年起",
      places: "羅馬 · 君士坦丁堡 · 亞歷山大 · 安條克",
      data: baseMap("schism", "教會分裂", "CHURCH SCHISM", "1054 AD", schismGeo, null, null, schismGeo.center, {
        factions: { church: CHURCH, empire: EMPIRE },
        factionOrder: ["church", "empire"],
        narr_zh: "1054年羅馬與君士坦丁堡互相開除教籍，東西教會正式分裂。",
        narr_en: "In 1054 Rome and Constantinople excommunicated each other.",
        points: [pt("rome"), pt("constantinople"), pt("alexandria"), pt("antioch")],
        units: [
          {
            id: "rome_ch",
            faction: "church",
            kind: "command",
            crest: "shield",
            cf: true,
            name_zh: "羅馬教會",
            name_en: "Roman Church",
            track: [{ d: 1, lng: c("rome")[0], lat: c("rome")[1], s: 0, st: "hold" }, { d: 100, lng: c("rome")[0], lat: c("rome")[1], s: 0, st: "hold" }],
          },
          {
            id: "constantinople",
            faction: "empire",
            kind: "command",
            crest: "circle",
            cf: true,
            name_zh: "君士坦丁堡教會",
            name_en: "Constantinople Church",
            track: [{ d: 1, lng: c("constantinople")[0], lat: c("constantinople")[1], s: 0, st: "hold" }, { d: 100, lng: c("constantinople")[0], lat: c("constantinople")[1], s: 0, st: "hold" }],
          },
        ],
      }),
    },
  ];
};
